steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build', '-t',
      'us-central1-docker.pkg.dev/lexical-lock-484905-p0/java-backend-repo/java-backend:$COMMIT_SHA',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/lexical-lock-484905-p0/java-backend-repo/java-backend:$COMMIT_SHA'
    ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'java-backend',
      '--image=us-central1-docker.pkg.dev/lexical-lock-484905-p0/java-backend-repo/java-backend:$COMMIT_SHA',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]

images:
- 'us-central1-docker.pkg.dev/lexical-lock-484905-p0/java-backend-repo/java-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
